DefaultRules Class Reference
Default rules.
#include <DefaultRules.h>
Public Member Functions
DefaultRules ()
DefaultRules constructor.
virtual ~DefaultRules ()
DefaultRules destructor.
Player * CreatePlayers ()
Create players.
bool ValidPlaceTile (Field *field, Player *player, BlokusTile *tile, u8 x, u8 y)
Checks if a tile can be placed at a certain location.
void PlacedTile (Field *field, Player *player, BlokusTile *tile, u8 x, u8 y)
Called after a tile has been placed.
Detailed Description
Default rules.
The default Blokus rules
Definition at line 8 of file DefaultRules.h.
Constructor & Destructor Documentation
DefaultRules::DefaultRules ()
DefaultRules constructor.
Sets field width, height, Player count and initialize standard tiles.
Definition at line 5 of file DefaultRules.cpp.
References Rules::FieldHeight, Rules::FieldWidth, and Rules::PlayerCount.
DefaultRules::~DefaultRules () [virtual]
DefaultRules destructor.
Destroy the standard tiles.
Definition at line 15 of file DefaultRules.cpp.
Member Function Documentation
Player * DefaultRules::CreatePlayers () [virtual]
Create players.
Allocates a list of players and gives them a TileSet.
Implements Rules .
Definition at line 204 of file DefaultRules.cpp.
References Rules::PlayerCount.
bool DefaultRules::ValidPlaceTile (Field * field, Player * player, BlokusTile * tile, u8 x, u8 y) [virtual]
Checks if a tile can be placed at a certain location.
Checks if a tile can be placed at a certain location, according to the official Blokus rules.
Implements Rules .
Definition at line 20 of file DefaultRules.cpp.
References Tile::Blocks, BlokusTile::getAmount(), Player::getTeam(), BlokusTile::getTileData(), Tile::Height, Player::PlacedFirstTile(), and Tile::Width.
void DefaultRules::PlacedTile (Field * field, Player * player, BlokusTile * tile, u8 x, u8 y) [virtual]
Called after a tile has been placed.
Removes a tile from the count and sets that player has used a tile.
Implements Rules .
Definition at line 198 of file DefaultRules.cpp.
References BlokusTile::getAmount(), BlokusTile::setAmount(), and Player::UsedTile().
The documentation for this class was generated from the following files:
DefaultRules.h
DefaultRules.cpp