Rules Class Reference
Rules.
#include <Rules.h>
Public Member Functions
virtual Field * CreateField ()
Create field.
virtual Player * CreatePlayers ()=0
Create players.
u8 getPlayerCount ()
Get player count.
virtual bool ValidPlaceTile (Field *field, Player *player, BlokusTile *tile, u8 x, u8 y)=0
Tells if tile can be placed at location.
virtual void PlacedTile (Field *field, Player *player, BlokusTile *tile, u8 x, u8 y)=0
Placed Tile.
Protected Attributes
u8 FieldWidth
u8 FieldHeight
u8 PlayerCount
Detailed Description
Rules.
Virtual base class. Handles creation of field, players etc..
Definition at line 10 of file Rules.h.
Member Function Documentation
virtual Field* Rules::CreateField () [inline, virtual]
Create field.
Allocates and returns a field.
Definition at line 15 of file Rules.h.
References Tile::Blocks, FieldHeight, FieldWidth, Tile::Height, and Tile::Width.
Referenced by Game::Game().
virtual Player* Rules::CreatePlayers () [pure virtual]
Create players.
Returns array of players.
Implemented in DefaultRules .
Referenced by Game::Game().
u8 Rules::getPlayerCount () [inline]
Get player count.
Returns player count.
Definition at line 30 of file Rules.h.
References PlayerCount.
Referenced by Game::Game().
virtual bool Rules::ValidPlaceTile (Field * field, Player * player, BlokusTile * tile, u8 x, u8 y) [pure virtual]
Tells if tile can be placed at location.
Returns true if the tile can be placed by player at the location.
Implemented in DefaultRules .
Referenced by Game::isValidPlace(), and Game::PlaceTile().
virtual void Rules::PlacedTile (Field * field, Player * player, BlokusTile * tile, u8 x, u8 y) [pure virtual]
Placed Tile.
Gets called by game after tile has been placed.
Implemented in DefaultRules .
Referenced by Game::PlaceTile().
The documentation for this class was generated from the following file:
Rules.h