wxBlokus Class Reference
Main frame for Blokus.
#include <wxBlokus.h>
Public Member Functions
wxBlokus (const wxString &title, const wxPoint &pos, const wxSize &size)
wxBlokus constructor
~wxBlokus ()
wxBlokus destructor
void OnQuit (wxCommandEvent &event)
Quit event.
void OnLoad (wxCommandEvent &event)
Load event.
void OnSave (wxCommandEvent &event)
Save event.
void OnAbout (wxCommandEvent &event)
About event.
void OnSkip (wxCommandEvent &event)
Skip event.
void OnCountScore (wxCommandEvent &event)
Count score event.
void OnNew (wxCommandEvent &event)
New event.
void KeyDown (wxKeyEvent &event)
KeyDown event.
void OnGameEnd ()
Game End callback.
void RefreshTilePanels ()
Refresh tile panels.
void ShowScore ()
ShowScore.
Static Public Member Functions
static void GameEnd ()
Static Game End callback.
Detailed Description
Main frame for Blokus.
Main window. Contains Rules and Game for gameplay mechanics. A FieldPanel, and a few instances of TilePanel show the previous, current and next Tile. This frame also handles key events from child windows and have a couple of commands from menus that allows players save, load, skip one's turn etc.
Definition at line 20 of file wxBlokus.h.
Constructor & Destructor Documentation
wxBlokus::wxBlokus (const wxString & title, const wxPoint & pos, const wxSize & size)
wxBlokus constructor
Allocates Game, Rules, and panels etc.
Definition at line 7 of file wxBlokus.cpp.
References GameEnd(), Game::getCurrentPlayer(), Player::getCurrentTile(), Player::getNextTile(), Player::getPreviousTile(), and Player::getTeam().
wxBlokus::~wxBlokus ()
wxBlokus destructor
Deletes game and rules.
Definition at line 89 of file wxBlokus.cpp.
Member Function Documentation
void wxBlokus::OnQuit (wxCommandEvent & event)
Quit event.
Closes the frame.
Definition at line 166 of file wxBlokus.cpp.
void wxBlokus::OnLoad (wxCommandEvent & event)
Load event.
Loads a previously saved game from file selector.
Definition at line 181 of file wxBlokus.cpp.
References Game::LoadGame(), and RefreshTilePanels().
void wxBlokus::OnSave (wxCommandEvent & event)
Save event.
Saves the current game.
Definition at line 198 of file wxBlokus.cpp.
References Game::SaveGame().
void wxBlokus::OnAbout (wxCommandEvent & event)
About event.
Displays Blokus information.
Definition at line 171 of file wxBlokus.cpp.
void wxBlokus::OnSkip (wxCommandEvent & event)
Skip event.
Closes the frame.
Definition at line 110 of file wxBlokus.cpp.
References Game::CyclePlayers(), and RefreshTilePanels().
void wxBlokus::OnCountScore (wxCommandEvent & event)
Count score event.
Displays the score in a message box.
Definition at line 156 of file wxBlokus.cpp.
References ShowScore().
void wxBlokus::OnNew (wxCommandEvent & event)
New event.
Resets the game.
Definition at line 119 of file wxBlokus.cpp.
References GameEnd(), RefreshTilePanels(), FieldPanel::setGame(), FieldPanel::setTileX(), and FieldPanel::setTileY().
void wxBlokus::KeyDown (wxKeyEvent & event)
KeyDown event.
Moves, changes and manipulates tiles based on key presses.
Definition at line 210 of file wxBlokus.cpp.
References Game::getCurrentPlayer(), Player::getCurrentTile(), Game::getField(), BlokusTile::getTileData(), FieldPanel::getTileX(), FieldPanel::getTileY(), Tile::Height, Game::PlaceTile(), RefreshTilePanels(), Player::setNextTile(), Player::setPreviousTile(), FieldPanel::setTileX(), FieldPanel::setTileY(), and Tile::Width.
void wxBlokus::OnGameEnd ()
Game End callback.
Displays the score in a message box.
Definition at line 161 of file wxBlokus.cpp.
References ShowScore().
Referenced by GameEnd().
void wxBlokus::RefreshTilePanels ()
Refresh tile panels.
Updates tile panels and has them redrawn.
Definition at line 95 of file wxBlokus.cpp.
References Game::getCurrentPlayer(), Player::getCurrentTile(), Player::getNextTile(), Player::getPreviousTile(), Player::getTeam(), TilePanel::setTeam(), and TilePanel::setTile().
Referenced by KeyDown(), OnLoad(), OnNew(), and OnSkip().
static void wxBlokus::GameEnd () [inline, static]
Static Game End callback.
Calls the current wxBlokus' GameEnd function.
Definition at line 73 of file wxBlokus.h.
References OnGameEnd().
Referenced by OnNew(), and wxBlokus().
void wxBlokus::ShowScore ()
ShowScore.
Displays the score in a message box.
Definition at line 136 of file wxBlokus.cpp.
References Game::getPlayer(), Game::getPlayerCount(), and Player::getScore().
Referenced by OnCountScore(), and OnGameEnd().
The documentation for this class was generated from the following files:
wxBlokus.h
wxBlokus.cpp