FieldPanel Class Reference
Field panel.
#include <FieldPanel.h>
Public Member Functions
FieldPanel (Game *game, wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
FieldPanel constructor.
void OnPaint (wxPaintEvent &event)
Paint event.
u8 getTileX ()
Gets X coordinate for the tile.
u8 getTileY ()
Gets Y coordinate for the tile.
void setTileX (u8 value)
Sets X coordinate for the tile.
void setTileY (u8 value)
Sets Y coordinate for the tile.
void setGame (Game *game)
Sets pointer to game.
Detailed Description
Field panel.
Displays a field.
Definition at line 9 of file FieldPanel.h.
Constructor & Destructor Documentation
FieldPanel::FieldPanel (Game * game, wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
FieldPanel constructor.
Shows itself, initialises and sets values.
Definition at line 10 of file FieldPanel.cpp.
Member Function Documentation
void FieldPanel::OnPaint (wxPaintEvent & event)
Paint event.
Paints out the field.
Definition at line 22 of file FieldPanel.cpp.
References Tile::Blocks, Game::getCurrentPlayer(), Player::getCurrentTile(), Game::getField(), Player::getTeam(), BlokusTile::getTileData(), Tile::Height, Game::isValidPlace(), and Tile::Width.
u8 FieldPanel::getTileX () [inline]
Gets X coordinate for the tile.
Gets the X coordinate for the displayed tile.
Definition at line 23 of file FieldPanel.h.
Referenced by wxBlokus::KeyDown().
u8 FieldPanel::getTileY () [inline]
Gets Y coordinate for the tile.
Gets the Y coordinate for the displayed tile.
Definition at line 27 of file FieldPanel.h.
Referenced by wxBlokus::KeyDown().
void FieldPanel::setTileX (u8 value) [inline]
Sets X coordinate for the tile.
Sets the X coordinate for the displayed tile.
Definition at line 31 of file FieldPanel.h.
Referenced by wxBlokus::KeyDown(), and wxBlokus::OnNew().
void FieldPanel::setTileY (u8 value) [inline]
Sets Y coordinate for the tile.
Sets the Y coordinate for the displayed tile.
Definition at line 35 of file FieldPanel.h.
Referenced by wxBlokus::KeyDown(), and wxBlokus::OnNew().
void FieldPanel::setGame (Game * game) [inline]
Sets pointer to game.
Sets the Game pointer from which the class reads.
Definition at line 39 of file FieldPanel.h.
Referenced by wxBlokus::OnNew().
The documentation for this class was generated from the following files:
FieldPanel.h
FieldPanel.cpp