TileSet Class Reference
Tile set.
#include <TileSet.h>
Public Member Functions
~TileSet ()
TileSet destructor.
u8 getNumTiles ()
Get number of tiles.
BlokusTile * getTile (u8 index)
Get a certain tile.
void setTile (u8 index, BlokusTile *tile)
Set a certain tile.
void setTileAmount (u8 tileAmount)
Set tile amount.
void setTileList (BlokusTile *tileList)
Set tile list.
Detailed Description
Tile set.
Tile set for the player, contains amount of tiles and which tiles they are.
Definition at line 8 of file TileSet.h.
Constructor & Destructor Documentation
TileSet::~TileSet () [inline]
TileSet destructor.
Deletes tiles.
Definition at line 13 of file TileSet.h.
Member Function Documentation
u8 TileSet::getNumTiles () [inline]
Get number of tiles.
Gets the amount of tiles in the set.
Definition at line 17 of file TileSet.h.
Referenced by Player::getScore(), Game::LoadGame(), Player::NextIndex(), Player::PreviousIndex(), Game::SaveGame(), and Player::setNextValidTile().
BlokusTile* TileSet::getTile (u8 index) [inline]
Get a certain tile.
Gets the requested tile.
Definition at line 21 of file TileSet.h.
Referenced by Player::getCurrentTile(), Player::getNextTile(), Player::getPreviousTile(), Player::getScore(), Game::LoadGame(), Game::SaveGame(), and Player::setNextValidTile().
void TileSet::setTile (u8 index, BlokusTile * tile) [inline]
Set a certain tile.
Overwrites a tile in the set to a specified one.
Definition at line 25 of file TileSet.h.
void TileSet::setTileAmount (u8 tileAmount) [inline]
Set tile amount.
Sets amount of tiles, used during creation.
Definition at line 31 of file TileSet.h.
void TileSet::setTileList (BlokusTile * tileList) [inline]
Set tile list.
Sets the pointer to a BlokusTile array.
Definition at line 35 of file TileSet.h.
The documentation for this class was generated from the following file:
TileSet.h