Game Class Reference
Game class.
#include <Game.h>
Public Member Functions
Game (Rules *rules, void(*endGameCallback)())
Game constructor.
~Game ()
Game destructor.
bool PlaceTile (BlokusTile *tile, u8 x, u8 y)
Place tile.
bool isValidPlace (BlokusTile *tile, u8 x, u8 y)
Checks if tile placement is valid.
Field * getField ()
Get Field.
Rules * getRules ()
Get Rield.
u8 getPlayerCount ()
Get Player count.
Player * getPlayerList ()
Get Player list.
Player * getCurrentPlayer ()
Get current Player.
Player * getPlayer (u8 index)
Get Player.
void CyclePlayers ()
Cycle players.
void EndGame ()
End game.
bool SaveGame (const char *path)
Save game.
bool LoadGame (const char *path)
Load game.
Detailed Description
Game class.
Most game-related stuff happens here.
Definition at line 10 of file Game.h.
Constructor & Destructor Documentation
Game::Game (Rules * rules, void(*)() endGameCallback)
Game constructor.
Has all game components allocated by Rules.
Definition at line 5 of file Game.cpp.
References Rules::CreateField(), Rules::CreatePlayers(), and Rules::getPlayerCount().
Game::~Game ()
Game destructor.
Destroys field and players.
Definition at line 20 of file Game.cpp.
Member Function Documentation
bool Game::PlaceTile (BlokusTile * tile, u8 x, u8 y)
Place tile.
Places a tile if possible.
Definition at line 29 of file Game.cpp.
References Tile::Blocks, CyclePlayers(), EndGame(), getCurrentPlayer(), Player::getTeam(), BlokusTile::getTileData(), Tile::Height, Rules::PlacedTile(), Rules::ValidPlaceTile(), and Tile::Width.
Referenced by wxBlokus::KeyDown().
bool Game::isValidPlace (BlokusTile * tile, u8 x, u8 y) [inline]
Checks if tile placement is valid.
Calls GameRules::ValidPlaceTile, returns true if tile placement is valid.
Definition at line 28 of file Game.h.
References getCurrentPlayer(), and Rules::ValidPlaceTile().
Referenced by FieldPanel::OnPaint().
Field* Game::getField () [inline]
Get Field.
Returns field.
Definition at line 32 of file Game.h.
Referenced by wxBlokus::KeyDown(), and FieldPanel::OnPaint().
Rules* Game::getRules () [inline]
Get Rield.
Returns current Rules.
Definition at line 36 of file Game.h.
u8 Game::getPlayerCount () [inline]
Get Player count.
Returns player count.
Definition at line 40 of file Game.h.
Referenced by wxBlokus::ShowScore().
Player* Game::getPlayerList () [inline]
Get Player list.
Returns pointer to player list.
Definition at line 44 of file Game.h.
Player* Game::getCurrentPlayer () [inline]
Get current Player.
Returns pointer to current player.
Definition at line 48 of file Game.h.
Referenced by isValidPlace(), wxBlokus::KeyDown(), FieldPanel::OnPaint(), PlaceTile(), wxBlokus::RefreshTilePanels(), and wxBlokus::wxBlokus().
Player* Game::getPlayer (u8 index) [inline]
Get Player.
Returns pointer to requested player.
Definition at line 52 of file Game.h.
Referenced by LoadGame(), SaveGame(), and wxBlokus::ShowScore().
void Game::CyclePlayers () [inline]
Cycle players.
Sets next player as current.
Definition at line 56 of file Game.h.
Referenced by wxBlokus::OnSkip(), and PlaceTile().
void Game::EndGame () [inline]
End game.
Calls endgame callback.
Definition at line 66 of file Game.h.
Referenced by PlaceTile().
bool Game::SaveGame (const char * path)
Save game.
Saves current state to path.
Definition at line 74 of file Game.cpp.
References Tile::Blocks, BlokusTile::getAmount(), TileSet::getNumTiles(), getPlayer(), TileSet::getTile(), Tile::Height, Player::PlacedFirstTile(), and Tile::Width.
Referenced by wxBlokus::OnSave().
bool Game::LoadGame (const char * path)
Load game.
Loads previous state from path.
Definition at line 108 of file Game.cpp.
References Tile::Blocks, TileSet::getNumTiles(), getPlayer(), TileSet::getTile(), Tile::Height, BlokusTile::setAmount(), and Tile::Width.
Referenced by wxBlokus::OnLoad().
The documentation for this class was generated from the following files:
Game.h
Game.cpp