BlokusTile Class Reference
Blokus tile.
#include <BlokusTile.h>
Public Member Functions
u8 getAmount ()
Get amount.
void setAmount (u8 amount)
Set amount.
u8 getScore ()
Get score.
void setScore (u8 score)
Set score.
Tile * getTileData ()
Get Tile data.
void setTile (Tile *tile)
Set Tile data.
Protected Attributes
Tile * TileData
u8 Amount
u8 Score
Detailed Description
Blokus tile.
Wraps tile data and adds amount and score to it.
Definition at line 8 of file BlokusTile.h.
Member Function Documentation
u8 BlokusTile::getAmount () [inline]
Get amount.
Returns amount of tiles.
Definition at line 13 of file BlokusTile.h.
References Amount.
Referenced by Player::getScore(), TilePanel::OnPaint(), DefaultRules::PlacedTile(), Game::SaveGame(), Player::setNextValidTile(), and DefaultRules::ValidPlaceTile().
void BlokusTile::setAmount (u8 amount) [inline]
Set amount.
Sets amount of tiles.
Definition at line 17 of file BlokusTile.h.
References Amount.
Referenced by Game::LoadGame(), and DefaultRules::PlacedTile().
u8 BlokusTile::getScore () [inline]
Get score.
Gets score per tiles.
Definition at line 21 of file BlokusTile.h.
References Score.
Referenced by Player::getScore().
void BlokusTile::setScore (u8 score) [inline]
Set score.
Sets score per tiles.
Definition at line 25 of file BlokusTile.h.
References Score.
Tile* BlokusTile::getTileData () [inline]
Get Tile data.
Returns pointer to actual tile data.
Definition at line 29 of file BlokusTile.h.
References TileData.
Referenced by wxBlokus::KeyDown(), TilePanel::OnPaint(), FieldPanel::OnPaint(), Game::PlaceTile(), and DefaultRules::ValidPlaceTile().
void BlokusTile::setTile (Tile * tile) [inline]
Set Tile data.
Associates BlokusTile with actual data.
Definition at line 33 of file BlokusTile.h.
References TileData.
The documentation for this class was generated from the following file:
BlokusTile.h