TilePanel Class Reference
Tile panel.
#include <TilePanel.h>
Public Member Functions
TilePanel (BlokusTile *tile, u8 team, wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
TilePanel constructor.
void OnPaint (wxPaintEvent &event)
Paint event.
void setTeam (u8 team)
Set team.
void setTile (BlokusTile *tile)
Set Tile.
Detailed Description
Tile panel.
Displays a tile with color related to set team.
Definition at line 9 of file TilePanel.h.
Constructor & Destructor Documentation
TilePanel::TilePanel (BlokusTile * tile, u8 team, wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
TilePanel constructor.
Sets tile and team.
Definition at line 11 of file TilePanel.cpp.
Member Function Documentation
void TilePanel::OnPaint (wxPaintEvent & event)
Paint event.
Draws the tile.
Definition at line 21 of file TilePanel.cpp.
References Tile::Blocks, BlokusTile::getAmount(), BlokusTile::getTileData(), Tile::Height, and Tile::Width.
void TilePanel::setTeam (u8 team) [inline]
Set team.
Sets display team for the tile.
Definition at line 23 of file TilePanel.h.
Referenced by wxBlokus::RefreshTilePanels().
void TilePanel::setTile (BlokusTile * tile) [inline]
Set Tile.
Sets tile to be displayed.
Definition at line 27 of file TilePanel.h.
Referenced by wxBlokus::RefreshTilePanels().
The documentation for this class was generated from the following files:
TilePanel.h
TilePanel.cpp