Player Class Reference
Player.
#include <Player.h>
Public Member Functions
Player ()
Player constructor.
u8 getTeam ()
Get team.
void setTeam (u8 team)
Set team.
void setNextTile ()
Set next tile.
void setPreviousTile ()
Set previous tile.
BlokusTile * getPreviousTile ()
Get previous tile.
BlokusTile * getNextTile ()
Get next tile.
BlokusTile * getCurrentTile ()
Get current tile.
bool setNextValidTile ()
Set next valid tile.
TileSet * getTileSet ()
Get TileSet.
bool PlacedFirstTile ()
Gets player's placed first tile status.
void UsedTile ()
Used tile.
u16 getScore ()
Get score.
Protected Member Functions
u8 NextIndex ()
Next index.
u8 PreviousIndex ()
Previous index.
Protected Attributes
u8 Team
u8 TileIndex
TileSet Tiles
bool HasPlacedTile
Detailed Description
Player.
Contains information on a certain player.
Definition at line 11 of file Player.h.
Constructor & Destructor Documentation
Player::Player () [inline]
Player constructor.
Sets default properties.
Definition at line 16 of file Player.h.
References HasPlacedTile, setTeam(), and TileIndex.
Member Function Documentation
u8 Player::getTeam () [inline]
Get team.
Returns player's team.
Definition at line 21 of file Player.h.
References Team.
Referenced by FieldPanel::OnPaint(), Game::PlaceTile(), wxBlokus::RefreshTilePanels(), DefaultRules::ValidPlaceTile(), and wxBlokus::wxBlokus().
void Player::setTeam (u8 team) [inline]
Set team.
Sets player's team.
Definition at line 25 of file Player.h.
References Team.
Referenced by Player().
void Player::setNextTile () [inline]
Set next tile.
Sets next tile as current.
Definition at line 29 of file Player.h.
References NextIndex(), and TileIndex.
Referenced by wxBlokus::KeyDown().
void Player::setPreviousTile () [inline]
Set previous tile.
Sets previous tile as current.
Definition at line 33 of file Player.h.
References PreviousIndex(), and TileIndex.
Referenced by wxBlokus::KeyDown().
BlokusTile* Player::getPreviousTile () [inline]
Get previous tile.
Gets previous tile.
Definition at line 37 of file Player.h.
References TileSet::getTile(), PreviousIndex(), and Tiles.
Referenced by wxBlokus::RefreshTilePanels(), and wxBlokus::wxBlokus().
BlokusTile* Player::getNextTile () [inline]
Get next tile.
Gets next tile.
Definition at line 41 of file Player.h.
References TileSet::getTile(), NextIndex(), and Tiles.
Referenced by wxBlokus::RefreshTilePanels(), and wxBlokus::wxBlokus().
BlokusTile* Player::getCurrentTile () [inline]
Get current tile.
Gets current tile.
Definition at line 45 of file Player.h.
References TileSet::getTile(), TileIndex, and Tiles.
Referenced by wxBlokus::KeyDown(), FieldPanel::OnPaint(), wxBlokus::RefreshTilePanels(), setNextValidTile(), and wxBlokus::wxBlokus().
bool Player::setNextValidTile () [inline]
Set next valid tile.
Sets next valid tile as current, if there are any.
Definition at line 49 of file Player.h.
References BlokusTile::getAmount(), getCurrentTile(), TileSet::getNumTiles(), TileSet::getTile(), NextIndex(), TileIndex, and Tiles.
TileSet* Player::getTileSet () [inline]
Get TileSet.
Gets player's TileSet.
Definition at line 71 of file Player.h.
References Tiles.
bool Player::PlacedFirstTile () [inline]
Gets player's placed first tile status.
Returns true if the player has placed a tile, else false.
Definition at line 75 of file Player.h.
References HasPlacedTile.
Referenced by Game::SaveGame(), and DefaultRules::ValidPlaceTile().
void Player::UsedTile () [inline]
Used tile.
Sets player's tile as used.
Definition at line 79 of file Player.h.
References HasPlacedTile.
Referenced by DefaultRules::PlacedTile().
u16 Player::getScore () [inline]
Get score.
Calculates and returns player's score.
Definition at line 83 of file Player.h.
References BlokusTile::getAmount(), TileSet::getNumTiles(), BlokusTile::getScore(), TileSet::getTile(), and Tiles.
Referenced by wxBlokus::ShowScore().
u8 Player::NextIndex () [inline, protected]
Next index.
Returns next index.
Definition at line 98 of file Player.h.
References TileSet::getNumTiles(), TileIndex, and Tiles.
Referenced by getNextTile(), setNextTile(), and setNextValidTile().
u8 Player::PreviousIndex () [inline, protected]
Previous index.
Returns previous index.
Definition at line 107 of file Player.h.
References TileSet::getNumTiles(), TileIndex, and Tiles.
Referenced by getPreviousTile(), and setPreviousTile().
The documentation for this class was generated from the following file:
Player.h